syntax = "proto3";

package message;

option go_package = "./message";

//servicio para entregar las listas a los equipos
service Hokage {  
    rpc ObtenerListaAkatsukis (Empty) returns (ListaAkatsukis);
    rpc ReclamarRecompensa (SolicitudRecompensa) returns (ConfirmacionPago);
}

message Empty {}

message AkatsukiInfo {
    string nombre = 1;
    int32 ataque = 2;
    int32 vida = 3;
    string estado = 4;
    string recompensa = 5;
}

message ListaAkatsukis {
    repeated AkatsukiInfo enemigos = 1;
}

message SolicitudRecompensa {
    string nombreEquipo = 1;
    string nombreAkatsuki = 2;
}

message ConfirmacionPago {
    string mensaje = 1;
    float ryoPagados = 2;
}