// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: EquiposNinja/proto/combateAkatsuki.proto

package CombateAkatsuki

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CombateAkatsuki_IniciarCombate_FullMethodName = "/CombateAkatsuki.CombateAkatsuki/IniciarCombate"
)

// CombateAkatsukiClient is the client API for CombateAkatsuki service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CombateAkatsukiClient interface {
	IniciarCombate(ctx context.Context, in *IniciarCombateRequest, opts ...grpc.CallOption) (*IniciarCombateResult, error)
}

type combateAkatsukiClient struct {
	cc grpc.ClientConnInterface
}

func NewCombateAkatsukiClient(cc grpc.ClientConnInterface) CombateAkatsukiClient {
	return &combateAkatsukiClient{cc}
}

func (c *combateAkatsukiClient) IniciarCombate(ctx context.Context, in *IniciarCombateRequest, opts ...grpc.CallOption) (*IniciarCombateResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IniciarCombateResult)
	err := c.cc.Invoke(ctx, CombateAkatsuki_IniciarCombate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CombateAkatsukiServer is the server API for CombateAkatsuki service.
// All implementations must embed UnimplementedCombateAkatsukiServer
// for forward compatibility.
type CombateAkatsukiServer interface {
	IniciarCombate(context.Context, *IniciarCombateRequest) (*IniciarCombateResult, error)
	mustEmbedUnimplementedCombateAkatsukiServer()
}

// UnimplementedCombateAkatsukiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCombateAkatsukiServer struct{}

func (UnimplementedCombateAkatsukiServer) IniciarCombate(context.Context, *IniciarCombateRequest) (*IniciarCombateResult, error) {
	return nil, status.Error(codes.Unimplemented, "method IniciarCombate not implemented")
}
func (UnimplementedCombateAkatsukiServer) mustEmbedUnimplementedCombateAkatsukiServer() {}
func (UnimplementedCombateAkatsukiServer) testEmbeddedByValue()                         {}

// UnsafeCombateAkatsukiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CombateAkatsukiServer will
// result in compilation errors.
type UnsafeCombateAkatsukiServer interface {
	mustEmbedUnimplementedCombateAkatsukiServer()
}

func RegisterCombateAkatsukiServer(s grpc.ServiceRegistrar, srv CombateAkatsukiServer) {
	// If the following call panics, it indicates UnimplementedCombateAkatsukiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CombateAkatsuki_ServiceDesc, srv)
}

func _CombateAkatsuki_IniciarCombate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IniciarCombateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CombateAkatsukiServer).IniciarCombate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CombateAkatsuki_IniciarCombate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CombateAkatsukiServer).IniciarCombate(ctx, req.(*IniciarCombateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CombateAkatsuki_ServiceDesc is the grpc.ServiceDesc for CombateAkatsuki service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CombateAkatsuki_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CombateAkatsuki.CombateAkatsuki",
	HandlerType: (*CombateAkatsukiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IniciarCombate",
			Handler:    _CombateAkatsuki_IniciarCombate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "EquiposNinja/proto/combateAkatsuki.proto",
}
