// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: EquiposNinja/proto/dataHokage.proto

package DataHokage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_EquiposNinja_proto_dataHokage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_EquiposNinja_proto_dataHokage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_EquiposNinja_proto_dataHokage_proto_rawDescGZIP(), []int{0}
}

type AkatsukiInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Ataque        int32                  `protobuf:"varint,3,opt,name=ataque,proto3" json:"ataque,omitempty"`
	Vida          int32                  `protobuf:"varint,4,opt,name=vida,proto3" json:"vida,omitempty"`
	Estado        string                 `protobuf:"bytes,5,opt,name=estado,proto3" json:"estado,omitempty"`
	Recompensa    int32                  `protobuf:"varint,6,opt,name=recompensa,proto3" json:"recompensa,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AkatsukiInfo) Reset() {
	*x = AkatsukiInfo{}
	mi := &file_EquiposNinja_proto_dataHokage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AkatsukiInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AkatsukiInfo) ProtoMessage() {}

func (x *AkatsukiInfo) ProtoReflect() protoreflect.Message {
	mi := &file_EquiposNinja_proto_dataHokage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AkatsukiInfo.ProtoReflect.Descriptor instead.
func (*AkatsukiInfo) Descriptor() ([]byte, []int) {
	return file_EquiposNinja_proto_dataHokage_proto_rawDescGZIP(), []int{1}
}

func (x *AkatsukiInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AkatsukiInfo) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *AkatsukiInfo) GetAtaque() int32 {
	if x != nil {
		return x.Ataque
	}
	return 0
}

func (x *AkatsukiInfo) GetVida() int32 {
	if x != nil {
		return x.Vida
	}
	return 0
}

func (x *AkatsukiInfo) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *AkatsukiInfo) GetRecompensa() int32 {
	if x != nil {
		return x.Recompensa
	}
	return 0
}

type ListaAkatsukis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Akatsukis     []*AkatsukiInfo        `protobuf:"bytes,1,rep,name=akatsukis,proto3" json:"akatsukis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaAkatsukis) Reset() {
	*x = ListaAkatsukis{}
	mi := &file_EquiposNinja_proto_dataHokage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaAkatsukis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaAkatsukis) ProtoMessage() {}

func (x *ListaAkatsukis) ProtoReflect() protoreflect.Message {
	mi := &file_EquiposNinja_proto_dataHokage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaAkatsukis.ProtoReflect.Descriptor instead.
func (*ListaAkatsukis) Descriptor() ([]byte, []int) {
	return file_EquiposNinja_proto_dataHokage_proto_rawDescGZIP(), []int{2}
}

func (x *ListaAkatsukis) GetAkatsukis() []*AkatsukiInfo {
	if x != nil {
		return x.Akatsukis
	}
	return nil
}

type DatosEquipo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NombreEquipo  string                 `protobuf:"bytes,1,opt,name=nombre_equipo,json=nombreEquipo,proto3" json:"nombre_equipo,omitempty"`
	Ataque        int32                  `protobuf:"varint,2,opt,name=ataque,proto3" json:"ataque,omitempty"`
	Vida          int32                  `protobuf:"varint,3,opt,name=vida,proto3" json:"vida,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatosEquipo) Reset() {
	*x = DatosEquipo{}
	mi := &file_EquiposNinja_proto_dataHokage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatosEquipo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatosEquipo) ProtoMessage() {}

func (x *DatosEquipo) ProtoReflect() protoreflect.Message {
	mi := &file_EquiposNinja_proto_dataHokage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatosEquipo.ProtoReflect.Descriptor instead.
func (*DatosEquipo) Descriptor() ([]byte, []int) {
	return file_EquiposNinja_proto_dataHokage_proto_rawDescGZIP(), []int{3}
}

func (x *DatosEquipo) GetNombreEquipo() string {
	if x != nil {
		return x.NombreEquipo
	}
	return ""
}

func (x *DatosEquipo) GetAtaque() int32 {
	if x != nil {
		return x.Ataque
	}
	return 0
}

func (x *DatosEquipo) GetVida() int32 {
	if x != nil {
		return x.Vida
	}
	return 0
}

type EstadoCombate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EstadoFinal     string                 `protobuf:"bytes,1,opt,name=estado_final,json=estadoFinal,proto3" json:"estado_final,omitempty"`
	CombateIniciado bool                   `protobuf:"varint,2,opt,name=combate_iniciado,json=combateIniciado,proto3" json:"combate_iniciado,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EstadoCombate) Reset() {
	*x = EstadoCombate{}
	mi := &file_EquiposNinja_proto_dataHokage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstadoCombate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoCombate) ProtoMessage() {}

func (x *EstadoCombate) ProtoReflect() protoreflect.Message {
	mi := &file_EquiposNinja_proto_dataHokage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoCombate.ProtoReflect.Descriptor instead.
func (*EstadoCombate) Descriptor() ([]byte, []int) {
	return file_EquiposNinja_proto_dataHokage_proto_rawDescGZIP(), []int{4}
}

func (x *EstadoCombate) GetEstadoFinal() string {
	if x != nil {
		return x.EstadoFinal
	}
	return ""
}

func (x *EstadoCombate) GetCombateIniciado() bool {
	if x != nil {
		return x.CombateIniciado
	}
	return false
}

type SolicitudRecompensa struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NombreEquipo   string                 `protobuf:"bytes,1,opt,name=nombre_equipo,json=nombreEquipo,proto3" json:"nombre_equipo,omitempty"`
	IdAkatsuki     int32                  `protobuf:"varint,2,opt,name=id_akatsuki,json=idAkatsuki,proto3" json:"id_akatsuki,omitempty"`
	NombreAkatsuki string                 `protobuf:"bytes,3,opt,name=nombre_akatsuki,json=nombreAkatsuki,proto3" json:"nombre_akatsuki,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SolicitudRecompensa) Reset() {
	*x = SolicitudRecompensa{}
	mi := &file_EquiposNinja_proto_dataHokage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudRecompensa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudRecompensa) ProtoMessage() {}

func (x *SolicitudRecompensa) ProtoReflect() protoreflect.Message {
	mi := &file_EquiposNinja_proto_dataHokage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudRecompensa.ProtoReflect.Descriptor instead.
func (*SolicitudRecompensa) Descriptor() ([]byte, []int) {
	return file_EquiposNinja_proto_dataHokage_proto_rawDescGZIP(), []int{5}
}

func (x *SolicitudRecompensa) GetNombreEquipo() string {
	if x != nil {
		return x.NombreEquipo
	}
	return ""
}

func (x *SolicitudRecompensa) GetIdAkatsuki() int32 {
	if x != nil {
		return x.IdAkatsuki
	}
	return 0
}

func (x *SolicitudRecompensa) GetNombreAkatsuki() string {
	if x != nil {
		return x.NombreAkatsuki
	}
	return ""
}

type ConfirmacionPago struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	RyoPagados    int32                  `protobuf:"varint,2,opt,name=ryo_pagados,json=ryoPagados,proto3" json:"ryo_pagados,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmacionPago) Reset() {
	*x = ConfirmacionPago{}
	mi := &file_EquiposNinja_proto_dataHokage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmacionPago) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmacionPago) ProtoMessage() {}

func (x *ConfirmacionPago) ProtoReflect() protoreflect.Message {
	mi := &file_EquiposNinja_proto_dataHokage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmacionPago.ProtoReflect.Descriptor instead.
func (*ConfirmacionPago) Descriptor() ([]byte, []int) {
	return file_EquiposNinja_proto_dataHokage_proto_rawDescGZIP(), []int{6}
}

func (x *ConfirmacionPago) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *ConfirmacionPago) GetRyoPagados() int32 {
	if x != nil {
		return x.RyoPagados
	}
	return 0
}

var File_EquiposNinja_proto_dataHokage_proto protoreflect.FileDescriptor

const file_EquiposNinja_proto_dataHokage_proto_rawDesc = "" +
	"\n" +
	"#EquiposNinja/proto/dataHokage.proto\x12\n" +
	"DataHokage\"\a\n" +
	"\x05Empty\"\x9a\x01\n" +
	"\fAkatsukiInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x16\n" +
	"\x06ataque\x18\x03 \x01(\x05R\x06ataque\x12\x12\n" +
	"\x04vida\x18\x04 \x01(\x05R\x04vida\x12\x16\n" +
	"\x06estado\x18\x05 \x01(\tR\x06estado\x12\x1e\n" +
	"\n" +
	"recompensa\x18\x06 \x01(\x05R\n" +
	"recompensa\"H\n" +
	"\x0eListaAkatsukis\x126\n" +
	"\takatsukis\x18\x01 \x03(\v2\x18.DataHokage.AkatsukiInfoR\takatsukis\"^\n" +
	"\vDatosEquipo\x12#\n" +
	"\rnombre_equipo\x18\x01 \x01(\tR\fnombreEquipo\x12\x16\n" +
	"\x06ataque\x18\x02 \x01(\x05R\x06ataque\x12\x12\n" +
	"\x04vida\x18\x03 \x01(\x05R\x04vida\"]\n" +
	"\rEstadoCombate\x12!\n" +
	"\festado_final\x18\x01 \x01(\tR\vestadoFinal\x12)\n" +
	"\x10combate_iniciado\x18\x02 \x01(\bR\x0fcombateIniciado\"\x84\x01\n" +
	"\x13SolicitudRecompensa\x12#\n" +
	"\rnombre_equipo\x18\x01 \x01(\tR\fnombreEquipo\x12\x1f\n" +
	"\vid_akatsuki\x18\x02 \x01(\x05R\n" +
	"idAkatsuki\x12'\n" +
	"\x0fnombre_akatsuki\x18\x03 \x01(\tR\x0enombreAkatsuki\"M\n" +
	"\x10ConfirmacionPago\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\x12\x1f\n" +
	"\vryo_pagados\x18\x02 \x01(\x05R\n" +
	"ryoPagados2\xa5\x01\n" +
	"\x06Hokage\x12F\n" +
	"\x15ObtenerListaAkatsukis\x12\x11.DataHokage.Empty\x1a\x1a.DataHokage.ListaAkatsukis\x12S\n" +
	"\x12ReclamarRecompensa\x12\x1f.DataHokage.SolicitudRecompensa\x1a\x1c.DataHokage.ConfirmacionPagoB\x0eZ\f./DataHokageb\x06proto3"

var (
	file_EquiposNinja_proto_dataHokage_proto_rawDescOnce sync.Once
	file_EquiposNinja_proto_dataHokage_proto_rawDescData []byte
)

func file_EquiposNinja_proto_dataHokage_proto_rawDescGZIP() []byte {
	file_EquiposNinja_proto_dataHokage_proto_rawDescOnce.Do(func() {
		file_EquiposNinja_proto_dataHokage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_EquiposNinja_proto_dataHokage_proto_rawDesc), len(file_EquiposNinja_proto_dataHokage_proto_rawDesc)))
	})
	return file_EquiposNinja_proto_dataHokage_proto_rawDescData
}

var file_EquiposNinja_proto_dataHokage_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_EquiposNinja_proto_dataHokage_proto_goTypes = []any{
	(*Empty)(nil),               // 0: DataHokage.Empty
	(*AkatsukiInfo)(nil),        // 1: DataHokage.AkatsukiInfo
	(*ListaAkatsukis)(nil),      // 2: DataHokage.ListaAkatsukis
	(*DatosEquipo)(nil),         // 3: DataHokage.DatosEquipo
	(*EstadoCombate)(nil),       // 4: DataHokage.EstadoCombate
	(*SolicitudRecompensa)(nil), // 5: DataHokage.SolicitudRecompensa
	(*ConfirmacionPago)(nil),    // 6: DataHokage.ConfirmacionPago
}
var file_EquiposNinja_proto_dataHokage_proto_depIdxs = []int32{
	1, // 0: DataHokage.ListaAkatsukis.akatsukis:type_name -> DataHokage.AkatsukiInfo
	0, // 1: DataHokage.Hokage.ObtenerListaAkatsukis:input_type -> DataHokage.Empty
	5, // 2: DataHokage.Hokage.ReclamarRecompensa:input_type -> DataHokage.SolicitudRecompensa
	2, // 3: DataHokage.Hokage.ObtenerListaAkatsukis:output_type -> DataHokage.ListaAkatsukis
	6, // 4: DataHokage.Hokage.ReclamarRecompensa:output_type -> DataHokage.ConfirmacionPago
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_EquiposNinja_proto_dataHokage_proto_init() }
func file_EquiposNinja_proto_dataHokage_proto_init() {
	if File_EquiposNinja_proto_dataHokage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_EquiposNinja_proto_dataHokage_proto_rawDesc), len(file_EquiposNinja_proto_dataHokage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_EquiposNinja_proto_dataHokage_proto_goTypes,
		DependencyIndexes: file_EquiposNinja_proto_dataHokage_proto_depIdxs,
		MessageInfos:      file_EquiposNinja_proto_dataHokage_proto_msgTypes,
	}.Build()
	File_EquiposNinja_proto_dataHokage_proto = out.File
	file_EquiposNinja_proto_dataHokage_proto_goTypes = nil
	file_EquiposNinja_proto_dataHokage_proto_depIdxs = nil
}
