// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: EquiposNinja/proto/dataHokage.proto

package DataHokage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Hokage_ObtenerListaAkatsukis_FullMethodName = "/DataHokage.Hokage/ObtenerListaAkatsukis"
	Hokage_ReclamarRecompensa_FullMethodName    = "/DataHokage.Hokage/ReclamarRecompensa"
)

// HokageClient is the client API for Hokage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio para interactuar con el Hokage
type HokageClient interface {
	ObtenerListaAkatsukis(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListaAkatsukis, error)
	ReclamarRecompensa(ctx context.Context, in *SolicitudRecompensa, opts ...grpc.CallOption) (*ConfirmacionPago, error)
}

type hokageClient struct {
	cc grpc.ClientConnInterface
}

func NewHokageClient(cc grpc.ClientConnInterface) HokageClient {
	return &hokageClient{cc}
}

func (c *hokageClient) ObtenerListaAkatsukis(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListaAkatsukis, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListaAkatsukis)
	err := c.cc.Invoke(ctx, Hokage_ObtenerListaAkatsukis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hokageClient) ReclamarRecompensa(ctx context.Context, in *SolicitudRecompensa, opts ...grpc.CallOption) (*ConfirmacionPago, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmacionPago)
	err := c.cc.Invoke(ctx, Hokage_ReclamarRecompensa_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HokageServer is the server API for Hokage service.
// All implementations must embed UnimplementedHokageServer
// for forward compatibility.
//
// Servicio para interactuar con el Hokage
type HokageServer interface {
	ObtenerListaAkatsukis(context.Context, *Empty) (*ListaAkatsukis, error)
	ReclamarRecompensa(context.Context, *SolicitudRecompensa) (*ConfirmacionPago, error)
	mustEmbedUnimplementedHokageServer()
}

// UnimplementedHokageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHokageServer struct{}

func (UnimplementedHokageServer) ObtenerListaAkatsukis(context.Context, *Empty) (*ListaAkatsukis, error) {
	return nil, status.Error(codes.Unimplemented, "method ObtenerListaAkatsukis not implemented")
}
func (UnimplementedHokageServer) ReclamarRecompensa(context.Context, *SolicitudRecompensa) (*ConfirmacionPago, error) {
	return nil, status.Error(codes.Unimplemented, "method ReclamarRecompensa not implemented")
}
func (UnimplementedHokageServer) mustEmbedUnimplementedHokageServer() {}
func (UnimplementedHokageServer) testEmbeddedByValue()                {}

// UnsafeHokageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HokageServer will
// result in compilation errors.
type UnsafeHokageServer interface {
	mustEmbedUnimplementedHokageServer()
}

func RegisterHokageServer(s grpc.ServiceRegistrar, srv HokageServer) {
	// If the following call panics, it indicates UnimplementedHokageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Hokage_ServiceDesc, srv)
}

func _Hokage_ObtenerListaAkatsukis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HokageServer).ObtenerListaAkatsukis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hokage_ObtenerListaAkatsukis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HokageServer).ObtenerListaAkatsukis(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hokage_ReclamarRecompensa_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolicitudRecompensa)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HokageServer).ReclamarRecompensa(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hokage_ReclamarRecompensa_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HokageServer).ReclamarRecompensa(ctx, req.(*SolicitudRecompensa))
	}
	return interceptor(ctx, in, info, handler)
}

// Hokage_ServiceDesc is the grpc.ServiceDesc for Hokage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hokage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DataHokage.Hokage",
	HandlerType: (*HokageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ObtenerListaAkatsukis",
			Handler:    _Hokage_ObtenerListaAkatsukis_Handler,
		},
		{
			MethodName: "ReclamarRecompensa",
			Handler:    _Hokage_ReclamarRecompensa_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "EquiposNinja/proto/dataHokage.proto",
}
