services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    networks:
      - appnet

  producer:
    build:
      context: ./producer
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    networks:
      - appnet

  consumer:
    build:
      context: ./consumer
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    networks:
      - appnet

  lester:
    build:
      context: .
      dockerfile: Lester/Dockerfile
    container_name: lester
    ports:
      - "50051:50051"
    networks:
      - appnet

  michael:
    build:
      context: .           
      dockerfile: Michael/Dockerfile
    depends_on:
      - lester
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
