services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  akatsuki:
    build:
      context: ./Akatsuki
      dockerfile: dir/Dockerfile
    container_name: Akatsuki
    ports:
      - "5001:5001"
    environment:
      - "NAME=Akatsuki"
      - "PORT=5001"
      - "Anbu-IP=10.35.168.36:5001"
      - "EquiposNinja-IP=10.35.168.37:5001"
      - "Hokage-IP=10.35.168.38:5001"
      - "RABBITMQ-IP=10.35.168.36:5672"
  anbu:
    build:
      context: ./Anbu
      dockerfile: dir/Dockerfile
    container_name: Anbu
    ports:
      - "5001:5001"
    environment:
      - "NAME=Anbu"
      - "PORT=5001"
      - "Akatsuki-IP=10.35.168.35:5001"
      - "EquiposNinja-IP=10.35.168.37:5001"
      - "Hokage-IP=10.35.168.38:5001"
      - "RABBITMQ-IP=10.35.168.36:5672"
    depends_on:
      - rabbitmq

  equiposninja:
    build:
      context: ./EquiposNinja
      dockerfile: dir/Dockerfile
    container_name: EquiposNinja
    ports:
      - "5001:5001"
    environment:
      - "NAME=EquiposNinja"
      - "PORT=5001"
      - "Akatsuki-IP=10.35.168.35:5001"
      - "Anbu-IP=10.35.168.36:5001"
      - "Hokage-IP=10.35.168.38:5001"
      - "RABBITMQ-IP=10.35.168.36:5672"

  hokage:
    build:
      context: ./Hokage
      dockerfile: dir/Dockerfile
    container_name: Hokage
    ports:
      - "5001:5001"
    environment:
      - "NAME=Hokage"
      - "PORT=5001"
      - "Akatsuki-IP=10.35.168.35:5001"
      - "Anbu-IP=10.35.168.36:5001"
      - "EquiposNinja-IP=10.35.168.37:5001"
      - "RABBITMQ-IP=10.35.168.36:5672"
