services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  akatsuki:
    build:
      context: ./Akatsuki
    container_name: akatsuki
    ports:
      - "5001:5001"
    environment:
      - "NAME=Akatsuki"
      - "PORT=5001"
      - "Anbu-IP=10.35.168.36:5001"
      - "EquiposNinja-IP=10.35.168.37:5001"
      - "Hokage-IP=10.35.168.38:5001"
      - "RABBITMQ-IP=10.35.168.36:5672"
  anbu:
    build:
      context: ./Anbu
    container_name: anbu
    ports:
      - "5001:5001"
    environment:
      - "NAME=Anbu"
      - "PORT=5001"
      - "Akatsuki-IP=10.35.168.35:5001"
      - "EquiposNinja-IP=10.35.168.37:5001"
      - "Hokage-IP=10.35.168.38:5001"
      - "RABBITMQ-IP=10.35.168.36:5672"

  equiposninja:
    build:
      context: ./EquiposNinja
    container_name: equiposninja
    ports:
      - "5001:5001"
    environment:
      - "NAME=EquiposNinja"
      - "PORT=5001"
      - "Akatsuki-IP=10.35.168.35:5001"
      - "Anbu-IP=10.35.168.36:5001"
      - "Hokage-IP=10.35.168.38:5001"
      - "RABBITMQ-IP=10.35.168.36:5672"

  hokage:
    build:
      context: ./Hokage
    container_name: hokage
    ports:
      - "5001:5001"
    environment:
      - "NAME=Hokage"
      - "PORT=5001"
      - "Akatsuki-IP=10.35.168.35:5001"
      - "Anbu-IP=10.35.168.36:5001"
      - "EquiposNinja-IP=10.35.168.37:5001"
      - "RABBITMQ-IP=10.35.168.36:5672"
