// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: EquiposNinja/proto/dataAkatsuki.proto

package DataAkatsuki

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataAkatsuki_SubmitAkatsuki_FullMethodName = "/DataAkatsuki.DataAkatsuki/SubmitAkatsuki"
)

// DataAkatsukiClient is the client API for DataAkatsuki service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataAkatsukiClient interface {
	SubmitAkatsuki(ctx context.Context, in *DataAkatsukiRequest, opts ...grpc.CallOption) (*DataAkatsukiResponse, error)
}

type dataAkatsukiClient struct {
	cc grpc.ClientConnInterface
}

func NewDataAkatsukiClient(cc grpc.ClientConnInterface) DataAkatsukiClient {
	return &dataAkatsukiClient{cc}
}

func (c *dataAkatsukiClient) SubmitAkatsuki(ctx context.Context, in *DataAkatsukiRequest, opts ...grpc.CallOption) (*DataAkatsukiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataAkatsukiResponse)
	err := c.cc.Invoke(ctx, DataAkatsuki_SubmitAkatsuki_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataAkatsukiServer is the server API for DataAkatsuki service.
// All implementations must embed UnimplementedDataAkatsukiServer
// for forward compatibility.
type DataAkatsukiServer interface {
	SubmitAkatsuki(context.Context, *DataAkatsukiRequest) (*DataAkatsukiResponse, error)
	mustEmbedUnimplementedDataAkatsukiServer()
}

// UnimplementedDataAkatsukiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataAkatsukiServer struct{}

func (UnimplementedDataAkatsukiServer) SubmitAkatsuki(context.Context, *DataAkatsukiRequest) (*DataAkatsukiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitAkatsuki not implemented")
}
func (UnimplementedDataAkatsukiServer) mustEmbedUnimplementedDataAkatsukiServer() {}
func (UnimplementedDataAkatsukiServer) testEmbeddedByValue()                      {}

// UnsafeDataAkatsukiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataAkatsukiServer will
// result in compilation errors.
type UnsafeDataAkatsukiServer interface {
	mustEmbedUnimplementedDataAkatsukiServer()
}

func RegisterDataAkatsukiServer(s grpc.ServiceRegistrar, srv DataAkatsukiServer) {
	// If the following call panics, it indicates UnimplementedDataAkatsukiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataAkatsuki_ServiceDesc, srv)
}

func _DataAkatsuki_SubmitAkatsuki_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataAkatsukiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataAkatsukiServer).SubmitAkatsuki(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataAkatsuki_SubmitAkatsuki_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataAkatsukiServer).SubmitAkatsuki(ctx, req.(*DataAkatsukiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataAkatsuki_ServiceDesc is the grpc.ServiceDesc for DataAkatsuki service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataAkatsuki_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DataAkatsuki.DataAkatsuki",
	HandlerType: (*DataAkatsukiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitAkatsuki",
			Handler:    _DataAkatsuki_SubmitAkatsuki_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "EquiposNinja/proto/dataAkatsuki.proto",
}
