// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.12.4
// source: heist.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Solicitud struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"` // p.ej. "Dame un trabajo"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Solicitud) Reset() {
	*x = Solicitud{}
	mi := &file_heist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Solicitud) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Solicitud) ProtoMessage() {}

func (x *Solicitud) ProtoReflect() protoreflect.Message {
	mi := &file_heist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Solicitud.ProtoReflect.Descriptor instead.
func (*Solicitud) Descriptor() ([]byte, []int) {
	return file_heist_proto_rawDescGZIP(), []int{0}
}

func (x *Solicitud) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type Oferta struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Botin          int32                  `protobuf:"varint,1,opt,name=botin,proto3" json:"botin,omitempty"`
	ProbFranklin   int32                  `protobuf:"varint,2,opt,name=probFranklin,proto3" json:"probFranklin,omitempty"`
	ProbTrevor     int32                  `protobuf:"varint,3,opt,name=probTrevor,proto3" json:"probTrevor,omitempty"`
	RiesgoPolicial int32                  `protobuf:"varint,4,opt,name=riesgoPolicial,proto3" json:"riesgoPolicial,omitempty"`
	Disponible     bool                   `protobuf:"varint,5,opt,name=disponible,proto3" json:"disponible,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Oferta) Reset() {
	*x = Oferta{}
	mi := &file_heist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Oferta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oferta) ProtoMessage() {}

func (x *Oferta) ProtoReflect() protoreflect.Message {
	mi := &file_heist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oferta.ProtoReflect.Descriptor instead.
func (*Oferta) Descriptor() ([]byte, []int) {
	return file_heist_proto_rawDescGZIP(), []int{1}
}

func (x *Oferta) GetBotin() int32 {
	if x != nil {
		return x.Botin
	}
	return 0
}

func (x *Oferta) GetProbFranklin() int32 {
	if x != nil {
		return x.ProbFranklin
	}
	return 0
}

func (x *Oferta) GetProbTrevor() int32 {
	if x != nil {
		return x.ProbTrevor
	}
	return 0
}

func (x *Oferta) GetRiesgoPolicial() int32 {
	if x != nil {
		return x.RiesgoPolicial
	}
	return 0
}

func (x *Oferta) GetDisponible() bool {
	if x != nil {
		return x.Disponible
	}
	return false
}

type Decision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aceptada      bool                   `protobuf:"varint,1,opt,name=aceptada,proto3" json:"aceptada,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_heist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_heist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_heist_proto_rawDescGZIP(), []int{2}
}

func (x *Decision) GetAceptada() bool {
	if x != nil {
		return x.Aceptada
	}
	return false
}

type Respuesta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Respuesta) Reset() {
	*x = Respuesta{}
	mi := &file_heist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Respuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respuesta) ProtoMessage() {}

func (x *Respuesta) ProtoReflect() protoreflect.Message {
	mi := &file_heist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respuesta.ProtoReflect.Descriptor instead.
func (*Respuesta) Descriptor() ([]byte, []int) {
	return file_heist_proto_rawDescGZIP(), []int{3}
}

func (x *Respuesta) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type Riesgo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Risk          int32                  `protobuf:"varint,1,opt,name=risk,proto3" json:"risk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Riesgo) Reset() {
	*x = Riesgo{}
	mi := &file_heist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Riesgo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Riesgo) ProtoMessage() {}

func (x *Riesgo) ProtoReflect() protoreflect.Message {
	mi := &file_heist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Riesgo.ProtoReflect.Descriptor instead.
func (*Riesgo) Descriptor() ([]byte, []int) {
	return file_heist_proto_rawDescGZIP(), []int{4}
}

func (x *Riesgo) GetRisk() int32 {
	if x != nil {
		return x.Risk
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_heist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_heist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_heist_proto_rawDescGZIP(), []int{5}
}

var File_heist_proto protoreflect.FileDescriptor

const file_heist_proto_rawDesc = "" +
	"\n" +
	"\vheist.proto\x12\x05heist\"%\n" +
	"\tSolicitud\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\"\xaa\x01\n" +
	"\x06Oferta\x12\x14\n" +
	"\x05botin\x18\x01 \x01(\x05R\x05botin\x12\"\n" +
	"\fprobFranklin\x18\x02 \x01(\x05R\fprobFranklin\x12\x1e\n" +
	"\n" +
	"probTrevor\x18\x03 \x01(\x05R\n" +
	"probTrevor\x12&\n" +
	"\x0eriesgoPolicial\x18\x04 \x01(\x05R\x0eriesgoPolicial\x12\x1e\n" +
	"\n" +
	"disponible\x18\x05 \x01(\bR\n" +
	"disponible\"&\n" +
	"\bDecision\x12\x1a\n" +
	"\baceptada\x18\x01 \x01(\bR\baceptada\"%\n" +
	"\tRespuesta\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\"\x1c\n" +
	"\x06Riesgo\x12\x12\n" +
	"\x04risk\x18\x01 \x01(\x05R\x04risk\"\a\n" +
	"\x05Empty2\xa4\x01\n" +
	"\fHeistService\x122\n" +
	"\x0fSolicitarOferta\x12\x10.heist.Solicitud\x1a\r.heist.Oferta\x122\n" +
	"\rAceptarOferta\x12\x0f.heist.Decision\x1a\x10.heist.Respuesta\x12,\n" +
	"\rEstudiarGolpe\x12\r.heist.Riesgo\x1a\f.heist.EmptyB\x06Z\x04/;pbb\x06proto3"

var (
	file_heist_proto_rawDescOnce sync.Once
	file_heist_proto_rawDescData []byte
)

func file_heist_proto_rawDescGZIP() []byte {
	file_heist_proto_rawDescOnce.Do(func() {
		file_heist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_heist_proto_rawDesc), len(file_heist_proto_rawDesc)))
	})
	return file_heist_proto_rawDescData
}

var file_heist_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_heist_proto_goTypes = []any{
	(*Solicitud)(nil), // 0: heist.Solicitud
	(*Oferta)(nil),    // 1: heist.Oferta
	(*Decision)(nil),  // 2: heist.Decision
	(*Respuesta)(nil), // 3: heist.Respuesta
	(*Riesgo)(nil),    // 4: heist.Riesgo
	(*Empty)(nil),     // 5: heist.Empty
}
var file_heist_proto_depIdxs = []int32{
	0, // 0: heist.HeistService.SolicitarOferta:input_type -> heist.Solicitud
	2, // 1: heist.HeistService.AceptarOferta:input_type -> heist.Decision
	4, // 2: heist.HeistService.EstudiarGolpe:input_type -> heist.Riesgo
	1, // 3: heist.HeistService.SolicitarOferta:output_type -> heist.Oferta
	3, // 4: heist.HeistService.AceptarOferta:output_type -> heist.Respuesta
	5, // 5: heist.HeistService.EstudiarGolpe:output_type -> heist.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_heist_proto_init() }
func file_heist_proto_init() {
	if File_heist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_heist_proto_rawDesc), len(file_heist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_heist_proto_goTypes,
		DependencyIndexes: file_heist_proto_depIdxs,
		MessageInfos:      file_heist_proto_msgTypes,
	}.Build()
	File_heist_proto = out.File
	file_heist_proto_goTypes = nil
	file_heist_proto_depIdxs = nil
}
