// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: Hokage/proto/dataAkatsuki.proto

package DataAkatsuki

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataAkatsukiRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre           string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Ataque           int32                  `protobuf:"varint,3,opt,name=ataque,proto3" json:"ataque,omitempty"`
	Vida             int32                  `protobuf:"varint,4,opt,name=vida,proto3" json:"vida,omitempty"`
	Estado           string                 `protobuf:"bytes,5,opt,name=estado,proto3" json:"estado,omitempty"`
	EquipoCapturador string                 `protobuf:"bytes,6,opt,name=equipo_capturador,json=equipoCapturador,proto3" json:"equipo_capturador,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DataAkatsukiRequest) Reset() {
	*x = DataAkatsukiRequest{}
	mi := &file_Hokage_proto_dataAkatsuki_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataAkatsukiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataAkatsukiRequest) ProtoMessage() {}

func (x *DataAkatsukiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Hokage_proto_dataAkatsuki_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataAkatsukiRequest.ProtoReflect.Descriptor instead.
func (*DataAkatsukiRequest) Descriptor() ([]byte, []int) {
	return file_Hokage_proto_dataAkatsuki_proto_rawDescGZIP(), []int{0}
}

func (x *DataAkatsukiRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DataAkatsukiRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *DataAkatsukiRequest) GetAtaque() int32 {
	if x != nil {
		return x.Ataque
	}
	return 0
}

func (x *DataAkatsukiRequest) GetVida() int32 {
	if x != nil {
		return x.Vida
	}
	return 0
}

func (x *DataAkatsukiRequest) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *DataAkatsukiRequest) GetEquipoCapturador() string {
	if x != nil {
		return x.EquipoCapturador
	}
	return ""
}

type DataAkatsukiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataAkatsukiResponse) Reset() {
	*x = DataAkatsukiResponse{}
	mi := &file_Hokage_proto_dataAkatsuki_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataAkatsukiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataAkatsukiResponse) ProtoMessage() {}

func (x *DataAkatsukiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Hokage_proto_dataAkatsuki_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataAkatsukiResponse.ProtoReflect.Descriptor instead.
func (*DataAkatsukiResponse) Descriptor() ([]byte, []int) {
	return file_Hokage_proto_dataAkatsuki_proto_rawDescGZIP(), []int{1}
}

func (x *DataAkatsukiResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_Hokage_proto_dataAkatsuki_proto protoreflect.FileDescriptor

const file_Hokage_proto_dataAkatsuki_proto_rawDesc = "" +
	"\n" +
	"\x1fHokage/proto/dataAkatsuki.proto\x12\fDataAkatsuki\"\xae\x01\n" +
	"\x13DataAkatsukiRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x16\n" +
	"\x06ataque\x18\x03 \x01(\x05R\x06ataque\x12\x12\n" +
	"\x04vida\x18\x04 \x01(\x05R\x04vida\x12\x16\n" +
	"\x06estado\x18\x05 \x01(\tR\x06estado\x12+\n" +
	"\x11equipo_capturador\x18\x06 \x01(\tR\x10equipoCapturador\"0\n" +
	"\x14DataAkatsukiResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB\x10Z\x0e./DataAkatsukib\x06proto3"

var (
	file_Hokage_proto_dataAkatsuki_proto_rawDescOnce sync.Once
	file_Hokage_proto_dataAkatsuki_proto_rawDescData []byte
)

func file_Hokage_proto_dataAkatsuki_proto_rawDescGZIP() []byte {
	file_Hokage_proto_dataAkatsuki_proto_rawDescOnce.Do(func() {
		file_Hokage_proto_dataAkatsuki_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Hokage_proto_dataAkatsuki_proto_rawDesc), len(file_Hokage_proto_dataAkatsuki_proto_rawDesc)))
	})
	return file_Hokage_proto_dataAkatsuki_proto_rawDescData
}

var file_Hokage_proto_dataAkatsuki_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Hokage_proto_dataAkatsuki_proto_goTypes = []any{
	(*DataAkatsukiRequest)(nil),  // 0: DataAkatsuki.DataAkatsukiRequest
	(*DataAkatsukiResponse)(nil), // 1: DataAkatsuki.DataAkatsukiResponse
}
var file_Hokage_proto_dataAkatsuki_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Hokage_proto_dataAkatsuki_proto_init() }
func file_Hokage_proto_dataAkatsuki_proto_init() {
	if File_Hokage_proto_dataAkatsuki_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Hokage_proto_dataAkatsuki_proto_rawDesc), len(file_Hokage_proto_dataAkatsuki_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Hokage_proto_dataAkatsuki_proto_goTypes,
		DependencyIndexes: file_Hokage_proto_dataAkatsuki_proto_depIdxs,
		MessageInfos:      file_Hokage_proto_dataAkatsuki_proto_msgTypes,
	}.Build()
	File_Hokage_proto_dataAkatsuki_proto = out.File
	file_Hokage_proto_dataAkatsuki_proto_goTypes = nil
	file_Hokage_proto_dataAkatsuki_proto_depIdxs = nil
}
