// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: Akatsuki/proto/combateAkatsuki.proto

package CombateAkatsuki

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DatosEquipo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NombreEquipo  string                 `protobuf:"bytes,1,opt,name=nombre_equipo,json=nombreEquipo,proto3" json:"nombre_equipo,omitempty"`
	Ataque        int32                  `protobuf:"varint,2,opt,name=ataque,proto3" json:"ataque,omitempty"`
	Vida          int32                  `protobuf:"varint,3,opt,name=vida,proto3" json:"vida,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatosEquipo) Reset() {
	*x = DatosEquipo{}
	mi := &file_Akatsuki_proto_combateAkatsuki_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatosEquipo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatosEquipo) ProtoMessage() {}

func (x *DatosEquipo) ProtoReflect() protoreflect.Message {
	mi := &file_Akatsuki_proto_combateAkatsuki_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatosEquipo.ProtoReflect.Descriptor instead.
func (*DatosEquipo) Descriptor() ([]byte, []int) {
	return file_Akatsuki_proto_combateAkatsuki_proto_rawDescGZIP(), []int{0}
}

func (x *DatosEquipo) GetNombreEquipo() string {
	if x != nil {
		return x.NombreEquipo
	}
	return ""
}

func (x *DatosEquipo) GetAtaque() int32 {
	if x != nil {
		return x.Ataque
	}
	return 0
}

func (x *DatosEquipo) GetVida() int32 {
	if x != nil {
		return x.Vida
	}
	return 0
}

type IniciarCombateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Equipo         *DatosEquipo           `protobuf:"bytes,1,opt,name=equipo,proto3" json:"equipo,omitempty"`
	IdObjetivo     int32                  `protobuf:"varint,2,opt,name=id_objetivo,json=idObjetivo,proto3" json:"id_objetivo,omitempty"`
	NombreObjetivo string                 `protobuf:"bytes,3,opt,name=nombre_objetivo,json=nombreObjetivo,proto3" json:"nombre_objetivo,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IniciarCombateRequest) Reset() {
	*x = IniciarCombateRequest{}
	mi := &file_Akatsuki_proto_combateAkatsuki_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IniciarCombateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IniciarCombateRequest) ProtoMessage() {}

func (x *IniciarCombateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Akatsuki_proto_combateAkatsuki_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IniciarCombateRequest.ProtoReflect.Descriptor instead.
func (*IniciarCombateRequest) Descriptor() ([]byte, []int) {
	return file_Akatsuki_proto_combateAkatsuki_proto_rawDescGZIP(), []int{1}
}

func (x *IniciarCombateRequest) GetEquipo() *DatosEquipo {
	if x != nil {
		return x.Equipo
	}
	return nil
}

func (x *IniciarCombateRequest) GetIdObjetivo() int32 {
	if x != nil {
		return x.IdObjetivo
	}
	return 0
}

func (x *IniciarCombateRequest) GetNombreObjetivo() string {
	if x != nil {
		return x.NombreObjetivo
	}
	return ""
}

type IniciarCombateResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IniciarCombateResult) Reset() {
	*x = IniciarCombateResult{}
	mi := &file_Akatsuki_proto_combateAkatsuki_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IniciarCombateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IniciarCombateResult) ProtoMessage() {}

func (x *IniciarCombateResult) ProtoReflect() protoreflect.Message {
	mi := &file_Akatsuki_proto_combateAkatsuki_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IniciarCombateResult.ProtoReflect.Descriptor instead.
func (*IniciarCombateResult) Descriptor() ([]byte, []int) {
	return file_Akatsuki_proto_combateAkatsuki_proto_rawDescGZIP(), []int{2}
}

func (x *IniciarCombateResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_Akatsuki_proto_combateAkatsuki_proto protoreflect.FileDescriptor

const file_Akatsuki_proto_combateAkatsuki_proto_rawDesc = "" +
	"\n" +
	"$Akatsuki/proto/combateAkatsuki.proto\x12\x0fCombateAkatsuki\"^\n" +
	"\vDatosEquipo\x12#\n" +
	"\rnombre_equipo\x18\x01 \x01(\tR\fnombreEquipo\x12\x16\n" +
	"\x06ataque\x18\x02 \x01(\x05R\x06ataque\x12\x12\n" +
	"\x04vida\x18\x03 \x01(\x05R\x04vida\"\x97\x01\n" +
	"\x15IniciarCombateRequest\x124\n" +
	"\x06equipo\x18\x01 \x01(\v2\x1c.CombateAkatsuki.DatosEquipoR\x06equipo\x12\x1f\n" +
	"\vid_objetivo\x18\x02 \x01(\x05R\n" +
	"idObjetivo\x12'\n" +
	"\x0fnombre_objetivo\x18\x03 \x01(\tR\x0enombreObjetivo\"0\n" +
	"\x14IniciarCombateResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2r\n" +
	"\x0fCombateAkatsuki\x12_\n" +
	"\x0eIniciarCombate\x12&.CombateAkatsuki.IniciarCombateRequest\x1a%.CombateAkatsuki.IniciarCombateResultB\x13Z\x11./CombateAkatsukib\x06proto3"

var (
	file_Akatsuki_proto_combateAkatsuki_proto_rawDescOnce sync.Once
	file_Akatsuki_proto_combateAkatsuki_proto_rawDescData []byte
)

func file_Akatsuki_proto_combateAkatsuki_proto_rawDescGZIP() []byte {
	file_Akatsuki_proto_combateAkatsuki_proto_rawDescOnce.Do(func() {
		file_Akatsuki_proto_combateAkatsuki_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Akatsuki_proto_combateAkatsuki_proto_rawDesc), len(file_Akatsuki_proto_combateAkatsuki_proto_rawDesc)))
	})
	return file_Akatsuki_proto_combateAkatsuki_proto_rawDescData
}

var file_Akatsuki_proto_combateAkatsuki_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_Akatsuki_proto_combateAkatsuki_proto_goTypes = []any{
	(*DatosEquipo)(nil),           // 0: CombateAkatsuki.DatosEquipo
	(*IniciarCombateRequest)(nil), // 1: CombateAkatsuki.IniciarCombateRequest
	(*IniciarCombateResult)(nil),  // 2: CombateAkatsuki.IniciarCombateResult
}
var file_Akatsuki_proto_combateAkatsuki_proto_depIdxs = []int32{
	0, // 0: CombateAkatsuki.IniciarCombateRequest.equipo:type_name -> CombateAkatsuki.DatosEquipo
	1, // 1: CombateAkatsuki.CombateAkatsuki.IniciarCombate:input_type -> CombateAkatsuki.IniciarCombateRequest
	2, // 2: CombateAkatsuki.CombateAkatsuki.IniciarCombate:output_type -> CombateAkatsuki.IniciarCombateResult
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Akatsuki_proto_combateAkatsuki_proto_init() }
func file_Akatsuki_proto_combateAkatsuki_proto_init() {
	if File_Akatsuki_proto_combateAkatsuki_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Akatsuki_proto_combateAkatsuki_proto_rawDesc), len(file_Akatsuki_proto_combateAkatsuki_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Akatsuki_proto_combateAkatsuki_proto_goTypes,
		DependencyIndexes: file_Akatsuki_proto_combateAkatsuki_proto_depIdxs,
		MessageInfos:      file_Akatsuki_proto_combateAkatsuki_proto_msgTypes,
	}.Build()
	File_Akatsuki_proto_combateAkatsuki_proto = out.File
	file_Akatsuki_proto_combateAkatsuki_proto_goTypes = nil
	file_Akatsuki_proto_combateAkatsuki_proto_depIdxs = nil
}
