// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DatosEquipo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NombreEquipo  string                 `protobuf:"bytes,1,opt,name=nombreEquipo,proto3" json:"nombreEquipo,omitempty"`
	Ataque        int32                  `protobuf:"varint,2,opt,name=ataque,proto3" json:"ataque,omitempty"`
	Vida          int32                  `protobuf:"varint,3,opt,name=vida,proto3" json:"vida,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatosEquipo) Reset() {
	*x = DatosEquipo{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatosEquipo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatosEquipo) ProtoMessage() {}

func (x *DatosEquipo) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatosEquipo.ProtoReflect.Descriptor instead.
func (*DatosEquipo) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *DatosEquipo) GetNombreEquipo() string {
	if x != nil {
		return x.NombreEquipo
	}
	return ""
}

func (x *DatosEquipo) GetAtaque() int32 {
	if x != nil {
		return x.Ataque
	}
	return 0
}

func (x *DatosEquipo) GetVida() int32 {
	if x != nil {
		return x.Vida
	}
	return 0
}

type Equipos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ninja         *DatosEquipo           `protobuf:"bytes,1,opt,name=ninja,proto3" json:"ninja,omitempty"`
	Rival         *DatosEquipo           `protobuf:"bytes,2,opt,name=rival,proto3" json:"rival,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Equipos) Reset() {
	*x = Equipos{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Equipos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Equipos) ProtoMessage() {}

func (x *Equipos) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Equipos.ProtoReflect.Descriptor instead.
func (*Equipos) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *Equipos) GetNinja() *DatosEquipo {
	if x != nil {
		return x.Ninja
	}
	return nil
}

func (x *Equipos) GetRival() *DatosEquipo {
	if x != nil {
		return x.Rival
	}
	return nil
}

type EstadoCombate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EstadoFinal     string                 `protobuf:"bytes,1,opt,name=estadoFinal,proto3" json:"estadoFinal,omitempty"`
	CombateIniciado bool                   `protobuf:"varint,2,opt,name=combateIniciado,proto3" json:"combateIniciado,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EstadoCombate) Reset() {
	*x = EstadoCombate{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstadoCombate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoCombate) ProtoMessage() {}

func (x *EstadoCombate) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoCombate.ProtoReflect.Descriptor instead.
func (*EstadoCombate) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *EstadoCombate) GetEstadoFinal() string {
	if x != nil {
		return x.EstadoFinal
	}
	return ""
}

func (x *EstadoCombate) GetCombateIniciado() bool {
	if x != nil {
		return x.CombateIniciado
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\amessage\"]\n" +
	"\vDatosEquipo\x12\"\n" +
	"\fnombreEquipo\x18\x01 \x01(\tR\fnombreEquipo\x12\x16\n" +
	"\x06ataque\x18\x02 \x01(\x05R\x06ataque\x12\x12\n" +
	"\x04vida\x18\x03 \x01(\x05R\x04vida\"a\n" +
	"\aEquipos\x12*\n" +
	"\x05ninja\x18\x01 \x01(\v2\x14.message.DatosEquipoR\x05ninja\x12*\n" +
	"\x05rival\x18\x02 \x01(\v2\x14.message.DatosEquipoR\x05rival\"[\n" +
	"\rEstadoCombate\x12 \n" +
	"\vestadoFinal\x18\x01 \x01(\tR\vestadoFinal\x12(\n" +
	"\x0fcombateIniciado\x18\x02 \x01(\bR\x0fcombateIniciado\"\a\n" +
	"\x05Empty2D\n" +
	"\x0eIniciarCombate\x122\n" +
	"\x0eIniciarCombate\x12\x10.message.Equipos\x1a\x0e.message.EmptyB\vZ\t./messageb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_message_proto_goTypes = []any{
	(*DatosEquipo)(nil),   // 0: message.DatosEquipo
	(*Equipos)(nil),       // 1: message.Equipos
	(*EstadoCombate)(nil), // 2: message.EstadoCombate
	(*Empty)(nil),         // 3: message.Empty
}
var file_message_proto_depIdxs = []int32{
	0, // 0: message.Equipos.ninja:type_name -> message.DatosEquipo
	0, // 1: message.Equipos.rival:type_name -> message.DatosEquipo
	1, // 2: message.IniciarCombate.IniciarCombate:input_type -> message.Equipos
	3, // 3: message.IniciarCombate.IniciarCombate:output_type -> message.Empty
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
