// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: message.proto

package message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IniciarCombate_IniciarCombate_FullMethodName = "/message.IniciarCombate/IniciarCombate"
)

// IniciarCombateClient is the client API for IniciarCombate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IniciarCombateClient interface {
	IniciarCombate(ctx context.Context, in *Equipos, opts ...grpc.CallOption) (*Empty, error)
}

type iniciarCombateClient struct {
	cc grpc.ClientConnInterface
}

func NewIniciarCombateClient(cc grpc.ClientConnInterface) IniciarCombateClient {
	return &iniciarCombateClient{cc}
}

func (c *iniciarCombateClient) IniciarCombate(ctx context.Context, in *Equipos, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, IniciarCombate_IniciarCombate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IniciarCombateServer is the server API for IniciarCombate service.
// All implementations must embed UnimplementedIniciarCombateServer
// for forward compatibility.
type IniciarCombateServer interface {
	IniciarCombate(context.Context, *Equipos) (*Empty, error)
	mustEmbedUnimplementedIniciarCombateServer()
}

// UnimplementedIniciarCombateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIniciarCombateServer struct{}

func (UnimplementedIniciarCombateServer) IniciarCombate(context.Context, *Equipos) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IniciarCombate not implemented")
}
func (UnimplementedIniciarCombateServer) mustEmbedUnimplementedIniciarCombateServer() {}
func (UnimplementedIniciarCombateServer) testEmbeddedByValue()                        {}

// UnsafeIniciarCombateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IniciarCombateServer will
// result in compilation errors.
type UnsafeIniciarCombateServer interface {
	mustEmbedUnimplementedIniciarCombateServer()
}

func RegisterIniciarCombateServer(s grpc.ServiceRegistrar, srv IniciarCombateServer) {
	// If the following call pancis, it indicates UnimplementedIniciarCombateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IniciarCombate_ServiceDesc, srv)
}

func _IniciarCombate_IniciarCombate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Equipos)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IniciarCombateServer).IniciarCombate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IniciarCombate_IniciarCombate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IniciarCombateServer).IniciarCombate(ctx, req.(*Equipos))
	}
	return interceptor(ctx, in, info, handler)
}

// IniciarCombate_ServiceDesc is the grpc.ServiceDesc for IniciarCombate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IniciarCombate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.IniciarCombate",
	HandlerType: (*IniciarCombateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IniciarCombate",
			Handler:    _IniciarCombate_IniciarCombate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
