// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: heistFranklin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Solicitud struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	ProbFranklin  int32                  `protobuf:"varint,2,opt,name=probFranklin,proto3" json:"probFranklin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Solicitud) Reset() {
	*x = Solicitud{}
	mi := &file_heistFranklin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Solicitud) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Solicitud) ProtoMessage() {}

func (x *Solicitud) ProtoReflect() protoreflect.Message {
	mi := &file_heistFranklin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Solicitud.ProtoReflect.Descriptor instead.
func (*Solicitud) Descriptor() ([]byte, []int) {
	return file_heistFranklin_proto_rawDescGZIP(), []int{0}
}

func (x *Solicitud) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *Solicitud) GetProbFranklin() int32 {
	if x != nil {
		return x.ProbFranklin
	}
	return 0
}

type Resultado struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           bool                   `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resultado) Reset() {
	*x = Resultado{}
	mi := &file_heistFranklin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resultado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resultado) ProtoMessage() {}

func (x *Resultado) ProtoReflect() protoreflect.Message {
	mi := &file_heistFranklin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resultado.ProtoReflect.Descriptor instead.
func (*Resultado) Descriptor() ([]byte, []int) {
	return file_heistFranklin_proto_rawDescGZIP(), []int{1}
}

func (x *Resultado) GetRes() bool {
	if x != nil {
		return x.Res
	}
	return false
}

var File_heistFranklin_proto protoreflect.FileDescriptor

const file_heistFranklin_proto_rawDesc = "" +
	"\n" +
	"\x13heistFranklin.proto\x12\rheistFranklin\"I\n" +
	"\tSolicitud\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\x12\"\n" +
	"\fprobFranklin\x18\x02 \x01(\x05R\fprobFranklin\"\x1d\n" +
	"\tResultado\x12\x10\n" +
	"\x03res\x18\x01 \x01(\bR\x03res2a\n" +
	"\x14heistFranklinService\x12I\n" +
	"\x13RealizarDistraccion\x12\x18.heistFranklin.Solicitud\x1a\x18.heistFranklin.ResultadoB\x06Z\x04/;pbb\x06proto3"

var (
	file_heistFranklin_proto_rawDescOnce sync.Once
	file_heistFranklin_proto_rawDescData []byte
)

func file_heistFranklin_proto_rawDescGZIP() []byte {
	file_heistFranklin_proto_rawDescOnce.Do(func() {
		file_heistFranklin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_heistFranklin_proto_rawDesc), len(file_heistFranklin_proto_rawDesc)))
	})
	return file_heistFranklin_proto_rawDescData
}

var file_heistFranklin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_heistFranklin_proto_goTypes = []any{
	(*Solicitud)(nil), // 0: heistFranklin.Solicitud
	(*Resultado)(nil), // 1: heistFranklin.Resultado
}
var file_heistFranklin_proto_depIdxs = []int32{
	0, // 0: heistFranklin.heistFranklinService.RealizarDistraccion:input_type -> heistFranklin.Solicitud
	1, // 1: heistFranklin.heistFranklinService.RealizarDistraccion:output_type -> heistFranklin.Resultado
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_heistFranklin_proto_init() }
func file_heistFranklin_proto_init() {
	if File_heistFranklin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_heistFranklin_proto_rawDesc), len(file_heistFranklin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_heistFranklin_proto_goTypes,
		DependencyIndexes: file_heistFranklin_proto_depIdxs,
		MessageInfos:      file_heistFranklin_proto_msgTypes,
	}.Build()
	File_heistFranklin_proto = out.File
	file_heistFranklin_proto_goTypes = nil
	file_heistFranklin_proto_depIdxs = nil
}
