// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: heistFranklin.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HeistFranklinService_RealizarDistraccion_FullMethodName = "/heistFranklin.heistFranklinService/RealizarDistraccion"
	HeistFranklinService_RealizarAtraco_FullMethodName      = "/heistFranklin.heistFranklinService/RealizarAtraco"
)

// HeistFranklinServiceClient is the client API for HeistFranklinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HeistFranklinServiceClient interface {
	RealizarDistraccion(ctx context.Context, in *Solicitud, opts ...grpc.CallOption) (*Resultado, error)
	RealizarAtraco(ctx context.Context, in *SolicitudAtraco, opts ...grpc.CallOption) (*Resultado, error)
}

type heistFranklinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHeistFranklinServiceClient(cc grpc.ClientConnInterface) HeistFranklinServiceClient {
	return &heistFranklinServiceClient{cc}
}

func (c *heistFranklinServiceClient) RealizarDistraccion(ctx context.Context, in *Solicitud, opts ...grpc.CallOption) (*Resultado, error) {
	out := new(Resultado)
	err := c.cc.Invoke(ctx, HeistFranklinService_RealizarDistraccion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *heistFranklinServiceClient) RealizarAtraco(ctx context.Context, in *SolicitudAtraco, opts ...grpc.CallOption) (*Resultado, error) {
	out := new(Resultado)
	err := c.cc.Invoke(ctx, HeistFranklinService_RealizarAtraco_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HeistFranklinServiceServer is the server API for HeistFranklinService service.
// All implementations must embed UnimplementedHeistFranklinServiceServer
// for forward compatibility
type HeistFranklinServiceServer interface {
	RealizarDistraccion(context.Context, *Solicitud) (*Resultado, error)
	RealizarAtraco(context.Context, *SolicitudAtraco) (*Resultado, error)
	mustEmbedUnimplementedHeistFranklinServiceServer()
}

// UnimplementedHeistFranklinServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHeistFranklinServiceServer struct {
}

func (UnimplementedHeistFranklinServiceServer) RealizarDistraccion(context.Context, *Solicitud) (*Resultado, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RealizarDistraccion not implemented")
}
func (UnimplementedHeistFranklinServiceServer) RealizarAtraco(context.Context, *SolicitudAtraco) (*Resultado, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RealizarAtraco not implemented")
}
func (UnimplementedHeistFranklinServiceServer) mustEmbedUnimplementedHeistFranklinServiceServer() {}

// UnsafeHeistFranklinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HeistFranklinServiceServer will
// result in compilation errors.
type UnsafeHeistFranklinServiceServer interface {
	mustEmbedUnimplementedHeistFranklinServiceServer()
}

func RegisterHeistFranklinServiceServer(s grpc.ServiceRegistrar, srv HeistFranklinServiceServer) {
	s.RegisterService(&HeistFranklinService_ServiceDesc, srv)
}

func _HeistFranklinService_RealizarDistraccion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solicitud)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeistFranklinServiceServer).RealizarDistraccion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HeistFranklinService_RealizarDistraccion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeistFranklinServiceServer).RealizarDistraccion(ctx, req.(*Solicitud))
	}
	return interceptor(ctx, in, info, handler)
}

func _HeistFranklinService_RealizarAtraco_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolicitudAtraco)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeistFranklinServiceServer).RealizarAtraco(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HeistFranklinService_RealizarAtraco_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeistFranklinServiceServer).RealizarAtraco(ctx, req.(*SolicitudAtraco))
	}
	return interceptor(ctx, in, info, handler)
}

// HeistFranklinService_ServiceDesc is the grpc.ServiceDesc for HeistFranklinService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HeistFranklinService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "heistFranklin.heistFranklinService",
	HandlerType: (*HeistFranklinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RealizarDistraccion",
			Handler:    _HeistFranklinService_RealizarDistraccion_Handler,
		},
		{
			MethodName: "RealizarAtraco",
			Handler:    _HeistFranklinService_RealizarAtraco_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "heistFranklin.proto",
}
