syntax = "proto3";

option go_package = "./CombateAkatsuki";
package CombateAkatsuki;

//
service CombateAkatsuki {
    //
    rpc IniciarCombate (IniciarCombateRequest) returns (IniciarCombateResult);
    //
    rpc LiberarAkatsuki (LiberarAkatsukiRequest) returns (LiberarAkatsukiResult);
}

message DatosEquipo {
    string nombre_equipo = 1;
    int32 ataque = 2;
    int32 vida = 3;
}

message IniciarCombateRequest {
    DatosEquipo equipo = 1;
    int32 id_objetivo = 2;
    string nombre_objetivo = 3;
}

message IniciarCombateResult {
    bool success = 1;
}

message LiberarAkatsukiRequest {
    int32 id_akatsuki = 1;
    string nombre_akatsuki = 2;
}

message LiberarAkatsukiResult {
    bool success = 1;
}