// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

type AkatsukiInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nombre        string                 `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Ataque        int32                  `protobuf:"varint,2,opt,name=ataque,proto3" json:"ataque,omitempty"`
	Vida          int32                  `protobuf:"varint,3,opt,name=vida,proto3" json:"vida,omitempty"`
	Estado        string                 `protobuf:"bytes,4,opt,name=estado,proto3" json:"estado,omitempty"`
	Recompensa    string                 `protobuf:"bytes,5,opt,name=recompensa,proto3" json:"recompensa,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AkatsukiInfo) Reset() {
	*x = AkatsukiInfo{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AkatsukiInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AkatsukiInfo) ProtoMessage() {}

func (x *AkatsukiInfo) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AkatsukiInfo.ProtoReflect.Descriptor instead.
func (*AkatsukiInfo) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *AkatsukiInfo) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *AkatsukiInfo) GetAtaque() int32 {
	if x != nil {
		return x.Ataque
	}
	return 0
}

func (x *AkatsukiInfo) GetVida() int32 {
	if x != nil {
		return x.Vida
	}
	return 0
}

func (x *AkatsukiInfo) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *AkatsukiInfo) GetRecompensa() string {
	if x != nil {
		return x.Recompensa
	}
	return ""
}

type ListaAkatsukis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enemigos      []*AkatsukiInfo        `protobuf:"bytes,1,rep,name=enemigos,proto3" json:"enemigos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaAkatsukis) Reset() {
	*x = ListaAkatsukis{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaAkatsukis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaAkatsukis) ProtoMessage() {}

func (x *ListaAkatsukis) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaAkatsukis.ProtoReflect.Descriptor instead.
func (*ListaAkatsukis) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *ListaAkatsukis) GetEnemigos() []*AkatsukiInfo {
	if x != nil {
		return x.Enemigos
	}
	return nil
}

type DatosEquipo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NombreEquipo  string                 `protobuf:"bytes,1,opt,name=nombreEquipo,proto3" json:"nombreEquipo,omitempty"`
	Ataque        int32                  `protobuf:"varint,2,opt,name=ataque,proto3" json:"ataque,omitempty"`
	Vida          int32                  `protobuf:"varint,3,opt,name=vida,proto3" json:"vida,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatosEquipo) Reset() {
	*x = DatosEquipo{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatosEquipo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatosEquipo) ProtoMessage() {}

func (x *DatosEquipo) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatosEquipo.ProtoReflect.Descriptor instead.
func (*DatosEquipo) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *DatosEquipo) GetNombreEquipo() string {
	if x != nil {
		return x.NombreEquipo
	}
	return ""
}

func (x *DatosEquipo) GetAtaque() int32 {
	if x != nil {
		return x.Ataque
	}
	return 0
}

func (x *DatosEquipo) GetVida() int32 {
	if x != nil {
		return x.Vida
	}
	return 0
}

type EstadoCombate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EstadoFinal     string                 `protobuf:"bytes,1,opt,name=estadoFinal,proto3" json:"estadoFinal,omitempty"`
	CombateIniciado bool                   `protobuf:"varint,2,opt,name=combateIniciado,proto3" json:"combateIniciado,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EstadoCombate) Reset() {
	*x = EstadoCombate{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstadoCombate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoCombate) ProtoMessage() {}

func (x *EstadoCombate) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoCombate.ProtoReflect.Descriptor instead.
func (*EstadoCombate) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *EstadoCombate) GetEstadoFinal() string {
	if x != nil {
		return x.EstadoFinal
	}
	return ""
}

func (x *EstadoCombate) GetCombateIniciado() bool {
	if x != nil {
		return x.CombateIniciado
	}
	return false
}

type SolicitudRecompensa struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NombreEquipo   string                 `protobuf:"bytes,1,opt,name=nombreEquipo,proto3" json:"nombreEquipo,omitempty"`
	NombreAkatsuki string                 `protobuf:"bytes,2,opt,name=nombreAkatsuki,proto3" json:"nombreAkatsuki,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SolicitudRecompensa) Reset() {
	*x = SolicitudRecompensa{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudRecompensa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudRecompensa) ProtoMessage() {}

func (x *SolicitudRecompensa) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudRecompensa.ProtoReflect.Descriptor instead.
func (*SolicitudRecompensa) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *SolicitudRecompensa) GetNombreEquipo() string {
	if x != nil {
		return x.NombreEquipo
	}
	return ""
}

func (x *SolicitudRecompensa) GetNombreAkatsuki() string {
	if x != nil {
		return x.NombreAkatsuki
	}
	return ""
}

type ConfirmacionPago struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	RyoPagados    float32                `protobuf:"fixed32,2,opt,name=ryoPagados,proto3" json:"ryoPagados,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmacionPago) Reset() {
	*x = ConfirmacionPago{}
	mi := &file_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmacionPago) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmacionPago) ProtoMessage() {}

func (x *ConfirmacionPago) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmacionPago.ProtoReflect.Descriptor instead.
func (*ConfirmacionPago) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *ConfirmacionPago) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *ConfirmacionPago) GetRyoPagados() float32 {
	if x != nil {
		return x.RyoPagados
	}
	return 0
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\amessage\"\a\n" +
	"\x05Empty\"\x8a\x01\n" +
	"\fAkatsukiInfo\x12\x16\n" +
	"\x06nombre\x18\x01 \x01(\tR\x06nombre\x12\x16\n" +
	"\x06ataque\x18\x02 \x01(\x05R\x06ataque\x12\x12\n" +
	"\x04vida\x18\x03 \x01(\x05R\x04vida\x12\x16\n" +
	"\x06estado\x18\x04 \x01(\tR\x06estado\x12\x1e\n" +
	"\n" +
	"recompensa\x18\x05 \x01(\tR\n" +
	"recompensa\"C\n" +
	"\x0eListaAkatsukis\x121\n" +
	"\benemigos\x18\x01 \x03(\v2\x15.message.AkatsukiInfoR\benemigos\"]\n" +
	"\vDatosEquipo\x12\"\n" +
	"\fnombreEquipo\x18\x01 \x01(\tR\fnombreEquipo\x12\x16\n" +
	"\x06ataque\x18\x02 \x01(\x05R\x06ataque\x12\x12\n" +
	"\x04vida\x18\x03 \x01(\x05R\x04vida\"[\n" +
	"\rEstadoCombate\x12 \n" +
	"\vestadoFinal\x18\x01 \x01(\tR\vestadoFinal\x12(\n" +
	"\x0fcombateIniciado\x18\x02 \x01(\bR\x0fcombateIniciado\"a\n" +
	"\x13SolicitudRecompensa\x12\"\n" +
	"\fnombreEquipo\x18\x01 \x01(\tR\fnombreEquipo\x12&\n" +
	"\x0enombreAkatsuki\x18\x02 \x01(\tR\x0enombreAkatsuki\"L\n" +
	"\x10ConfirmacionPago\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\x12\x1e\n" +
	"\n" +
	"ryoPagados\x18\x02 \x01(\x02R\n" +
	"ryoPagados2\x99\x01\n" +
	"\x06Hokage\x12@\n" +
	"\x15ObtenerListaAkatsukis\x12\x0e.message.Empty\x1a\x17.message.ListaAkatsukis\x12M\n" +
	"\x12ReclamarRecompensa\x12\x1c.message.SolicitudRecompensa\x1a\x19.message.ConfirmacionPago2J\n" +
	"\bAkatsuki\x12>\n" +
	"\x0eIniciarCombate\x12\x14.message.DatosEquipo\x1a\x16.message.EstadoCombateB\vZ\t./messageb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_message_proto_goTypes = []any{
	(*Empty)(nil),               // 0: message.Empty
	(*AkatsukiInfo)(nil),        // 1: message.AkatsukiInfo
	(*ListaAkatsukis)(nil),      // 2: message.ListaAkatsukis
	(*DatosEquipo)(nil),         // 3: message.DatosEquipo
	(*EstadoCombate)(nil),       // 4: message.EstadoCombate
	(*SolicitudRecompensa)(nil), // 5: message.SolicitudRecompensa
	(*ConfirmacionPago)(nil),    // 6: message.ConfirmacionPago
}
var file_message_proto_depIdxs = []int32{
	1, // 0: message.ListaAkatsukis.enemigos:type_name -> message.AkatsukiInfo
	0, // 1: message.Hokage.ObtenerListaAkatsukis:input_type -> message.Empty
	5, // 2: message.Hokage.ReclamarRecompensa:input_type -> message.SolicitudRecompensa
	3, // 3: message.Akatsuki.IniciarCombate:input_type -> message.DatosEquipo
	2, // 4: message.Hokage.ObtenerListaAkatsukis:output_type -> message.ListaAkatsukis
	6, // 5: message.Hokage.ReclamarRecompensa:output_type -> message.ConfirmacionPago
	4, // 6: message.Akatsuki.IniciarCombate:output_type -> message.EstadoCombate
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
