// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: heistTrevor.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HeistTrevorService_RealizarDistraccion_FullMethodName = "/heistTrevor.heistTrevorService/RealizarDistraccion"
)

// HeistTrevorServiceClient is the client API for HeistTrevorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HeistTrevorServiceClient interface {
	RealizarDistraccion(ctx context.Context, in *Solicitud, opts ...grpc.CallOption) (*Resultado, error)
}

type heistTrevorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHeistTrevorServiceClient(cc grpc.ClientConnInterface) HeistTrevorServiceClient {
	return &heistTrevorServiceClient{cc}
}

func (c *heistTrevorServiceClient) RealizarDistraccion(ctx context.Context, in *Solicitud, opts ...grpc.CallOption) (*Resultado, error) {
	out := new(Resultado)
	err := c.cc.Invoke(ctx, HeistTrevorService_RealizarDistraccion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HeistTrevorServiceServer is the server API for HeistTrevorService service.
// All implementations must embed UnimplementedHeistTrevorServiceServer
// for forward compatibility
type HeistTrevorServiceServer interface {
	RealizarDistraccion(context.Context, *Solicitud) (*Resultado, error)
	mustEmbedUnimplementedHeistTrevorServiceServer()
}

// UnimplementedHeistTrevorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHeistTrevorServiceServer struct {
}

func (UnimplementedHeistTrevorServiceServer) RealizarDistraccion(context.Context, *Solicitud) (*Resultado, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RealizarDistraccion not implemented")
}
func (UnimplementedHeistTrevorServiceServer) mustEmbedUnimplementedHeistTrevorServiceServer() {}

// UnsafeHeistTrevorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HeistTrevorServiceServer will
// result in compilation errors.
type UnsafeHeistTrevorServiceServer interface {
	mustEmbedUnimplementedHeistTrevorServiceServer()
}

func RegisterHeistTrevorServiceServer(s grpc.ServiceRegistrar, srv HeistTrevorServiceServer) {
	s.RegisterService(&HeistTrevorService_ServiceDesc, srv)
}

func _HeistTrevorService_RealizarDistraccion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solicitud)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeistTrevorServiceServer).RealizarDistraccion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HeistTrevorService_RealizarDistraccion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeistTrevorServiceServer).RealizarDistraccion(ctx, req.(*Solicitud))
	}
	return interceptor(ctx, in, info, handler)
}

// HeistTrevorService_ServiceDesc is the grpc.ServiceDesc for HeistTrevorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HeistTrevorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "heistTrevor.heistTrevorService",
	HandlerType: (*HeistTrevorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RealizarDistraccion",
			Handler:    _HeistTrevorService_RealizarDistraccion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "heistTrevor.proto",
}
